### ISSUE TITLE
While selecting mp4 files, app keeps stopping.

### ISSUE THREAD

**Issue by k245sem** [Cyunrei/Video-Live-Wallpaper#2]
Hello, the app keeps stopping while i select the mp4 file. It is about 30 mb and if the mp4 file is selected Nothin displays and only a black screen is shown

**Comment by shahid-niazi** [comment]
I'm having same problem of black screen but on my side app is not stopping/crashing while selecting the .mp4 files. I have imported the projected to Android Studio.
