### ISSUE TITLE
Black screen after selecting the .mp4 files.

### ISSUE THREAD

**Issue by shahid-niazi** [Cyunrei/Video-Live-Wallpaper#3]
I'm having problem of black screen after selecting .mp4 files. I have imported the projected to Android Studio.

**Comment by getyoteamsolutions** [comment]
> I'm having problem of black screen after selecting .mp4 files. I have imported the projected to Android Studio.
@shahid-niazi 
can the above issue resolved...?
The same issue came in my phone.

**Comment by cyunrei** [comment]
I found that this issue occurred on Android 10, because Android 10 changed the file storage mode.This issue can be solved by adding android:requestLegacyExternalStorage="true" to line 13 of the newly released AndroidManifest.xml

**Comment by cyunrei** [comment]
@shahid-niazi I only found this issue on Android 10. Do you have this issue with Android version Android 10?
